<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

    const posts = [
    {title: 'post 1', body: 'This is post one', createdAt: new Date().getTime()},
    {title: 'post 2', body: 'This is post two', createdAt: new Date().getTime()}
];

let intervalId = 0;
function getPost() {
    clearInterval(intervalId);
    const timerId = setInterval(() => {
        let output = "";
        posts.forEach((post, index) => {
            output +=`<li>${post.title}  last updated ${Math.trunc((new Date().getTime() - post.createdAt) / 1000)}  seconds ago </li>`;
        });        
        document.body.innerHTML = output;
    }, 1000);
}


function createPost(post) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            posts.push({...post, createdAt: new Date().getTime()});
            const error = false;
            if(!error) {
                resolve();
            } else {
                reject('Error: something went wrong');
            }
        }, 1000);
    });
}

function deletePost() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            if(posts.length> 0) {
                const lastElement = posts.pop()
                resolve(lastElement);
            } else {
                reject('Array is empty now');
            }
        }, 3000);
    });
}

createPost({title: 'post 3', body: 'this is post three'})
.then(() => {
    getPost();
    deletePost().then(() => {
        getPost();
        deletePost().then(() => {
            getPost();
            deletePost().then(() => {})
            .catch((err) =>{
                console.log('inside catch block', err)
            })
        })
        .catch((err) =>{
            console.log('inside catch block',err)
        })
    }).catch((err) =>{ 
        console.log('inside a catch block', err)
    })
})
.catch(err => console.log(err));

    </script>
</body>
</html>